In [1]:
 #Pruebas de TeamMaker
# importing the sys module
import sys        
 
# appending the directory of mod.py
# in the sys.path list
sys.path.append('C:/Users/fteje/Documents/Code/aicolearn/aicolearn/')       
 
# now we can import mod
import teammaker  
import numpy as np 
from sklearn.cluster import KMeans

 


In [2]:
# Definimos un array de características numéricas:
# Alumno 1, Alumno 2, Alumno 3, Alumno 4, Alumno 5, Alumno 6, Alumno 7, Alumno 8
NombresAlumnos = ["Alumno 1","Alumno 2","Alumno 3","Alumno 4","Alumno 5","Alumno 6","Alumno 7","Alumno 8"]

In [3]:
NombresAlumnos

['Alumno 1',
 'Alumno 2',
 'Alumno 3',
 'Alumno 4',
 'Alumno 5',
 'Alumno 6',
 'Alumno 7',
 'Alumno 8']

In [4]:
# Creamos las cabeceras
Caracteristicas = ["Edad","Sexo","NotaMedia"]

# Creamos los tipos de alumnos
DatosTipoAlumno1 = [23,1,9.8]
DatosTipoAlumno2 = [19,0,5.5]
DatosTipoAlumno3 = [20,1,7.0]

# Creamos la lista de alumnos
AlumnosTipo = [DatosTipoAlumno1,DatosTipoAlumno2,DatosTipoAlumno3,DatosTipoAlumno1,DatosTipoAlumno2,DatosTipoAlumno3,DatosTipoAlumno1,DatosTipoAlumno2]

In [5]:
# Creamos el array de pruebas de alumnos
AlumnosTipo

[[23, 1, 9.8],
 [19, 0, 5.5],
 [20, 1, 7.0],
 [23, 1, 9.8],
 [19, 0, 5.5],
 [20, 1, 7.0],
 [23, 1, 9.8],
 [19, 0, 5.5]]

In [6]:
npAlumnos = np.array(AlumnosTipo)

In [7]:
npAlumnos

array([[23. ,  1. ,  9.8],
       [19. ,  0. ,  5.5],
       [20. ,  1. ,  7. ],
       [23. ,  1. ,  9.8],
       [19. ,  0. ,  5.5],
       [20. ,  1. ,  7. ],
       [23. ,  1. ,  9.8],
       [19. ,  0. ,  5.5]])

In [169]:
# Vamos a buscar 3 clusters
KM = KMeans(n_clusters=2, init='k-means++', random_state=0, n_init="auto").fit(npAlumnos)


C:\Users\fteje\anaconda3\envs\DesarrolloDjango\Lib\site-packages\sklearn\cluster\_kmeans.py:1382: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(


In [170]:
centroides = KM.cluster_centers_

In [171]:
centroides

array([[19.4,  0.4,  6.1],
       [23. ,  1. ,  9.8]])

In [172]:
KM.get_feature_names_out()

array(['kmeans0', 'kmeans1'], dtype=object)

In [173]:
#Número de características tenidas en cuenta
KM.n_features_in_

3

In [174]:
KM.labels_

array([1, 0, 0, 1, 0, 0, 1, 0])

In [175]:
#Vamos a hacer una predicción
KM.predict([[19. ,  0. ,  5.5]])

array([0])